steps:
- name: gcr.io/cloud-builders/docker
  args:
    - run
    - '--privileged'
    - 'linuxkit/binfmt:v0.8'
  id: initialize-qemu
- name: gcr.io/cloud-builders/docker
  args:
    - buildx
    - create
    - '--name'
    - buildxbuilder
  id: create-builder
- name: gcr.io/cloud-builders/docker
  args:
    - buildx
    - use
    - buildxbuilder
  id: select-builder
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/bob-build:latest']
  id: pull-build
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/bob:latest']
  id: pull-app
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'buildx'
  - 'build'
  - '--platform'
  - 'linux/amd64,linux/arm64'
  - '-t'
  - 'gcr.io/$PROJECT_ID/bob-build:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/bob-build:$SHORT_SHA'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/bob-build:latest'
  - '--target'
  - 'build'
  - '.'
  id: build-build
  waitFor: ['pull-build', 'select-builder']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'buildx'
  - 'build'
  - '--platform'
  - 'linux/amd64,linux/arm64'
  - '-t'
  - 'gcr.io/$PROJECT_ID/bob:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/bob:$SHORT_SHA'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/bob-build:latest'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/bob:latest'
  - '--target'
  - 'app'
  - '.'
  id: build-app
  waitFor: ['build-build', 'pull-app', 'select-builder']

images:
- 'gcr.io/$PROJECT_ID/bob-build:latest'
- 'gcr.io/$PROJECT_ID/bob:latest'
- 'gcr.io/$PROJECT_ID/bob-build:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/bob:$SHORT_SHA'

options:
  env:
    - DOCKER_CLI_EXPERIMENTAL=enabled
  machineType: 'N1_HIGHCPU_8'

